# Generated by Django 4.1 on 2022-08-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=255)),
                ('curso', models.CharField(max_length=255)),
            ],
        ),
    ]
