# Generated by Django 4.1 on 2022-08-09 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'alunos',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('matriz', models.CharField(max_length=255)),
                ('codigo', models.BigIntegerField()),
                ('campus', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('descr_materia', models.CharField(max_length=500)),
                ('horas', models.IntegerField()),
                ('creditos', models.IntegerField()),
                ('situacao', models.CharField(blank=True, max_length=255, null=True)),
                ('mp', models.CharField(blank=True, max_length=10, null=True)),
                ('mf', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'materiais',
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('semestre', models.CharField(max_length=6)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to='alunos.aluno')),
                ('cursos', models.ManyToManyField(related_name='cursos', to='alunos.curso')),
            ],
            options={
                'db_table': 'semestres',
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('descr_avaliacao', models.CharField(max_length=50)),
                ('nota', models.CharField(max_length=10)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='alunos.materia')),
            ],
            options={
                'db_table': 'notas',
            },
        ),
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('dia', models.DateField()),
                ('faltas', models.IntegerField()),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas', to='alunos.materia')),
            ],
            options={
                'db_table': 'faltas',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='materias',
            field=models.ManyToManyField(related_name='materias', to='alunos.materia'),
        ),
    ]
