# Generated by Django 4.1 on 2022-08-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
