# Generated by Django 4.1 on 2022-08-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='descr_curso',
            field=models.CharField(default='', max_length=500),
        ),
    ]
